### ISSUE TITLE
For small screen size , the width of Team photos is too small. 

### ISSUE THREAD

**Issue by amaan-aly246** [amaan-aly246/Enactus-website#19]
For the small screen size the width of team member photo is too small.
Adjust Team member photos on the Team page to appear more square-like (not necessarily exact squares).
![Screenshot 2024-12-22 045058](https://github.com/user-attachments/assets/3fa1ebb5-b1a3-4175-b5f0-2c986ee10463)

**Comment by mohamedhesham221** [comment]
assign it to me .
